[book]
authors = ["Diego Marcano"]
language = "en"
multilingual = false
src = "src"
title = "Automatic Differentiation: Brief Overview"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
mathjax-support = true

[output.html.playground]
editable = true
default-theme = "rust"

