[book]
authors = ["Diego Marcano"]
language = "en"
multilingual = false
src = "src"
title = "Automatic Differentiation: Brief Overview"

[output.html]
mathjax-support = true

[output.html.playground]
editable = true